name: 6(弃用) output epgnew4gtv2_cst.xml

on:
  # schedule:
    # 每天0点30分、4点30分、8点30分、12点30分、16点30分、20点30分执行一次
  #  - cron: '30 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 第一步：创建临时工作目录
      - name: Create temp directory
        run: mkdir -p temp_workspace

      # 第二步：检出主分支（获取输入文件）
      - name: Checkout main branch for input file
        uses: actions/checkout@v4
        with:
          ref: main
          path: temp_workspace/main_repo

      # 第三步：检出脚本仓库的epg_scripts分支到临时目录
      - name: Checkout scripts from epg_scripts branch
        uses: actions/checkout@v4
        with:
          ref: epg_scripts
          path: temp_workspace/scripts

      # 第四步：设置 Python 环境（自动安装指定版本）
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 指定需要的 Python 版本

      # 第五步：安装 Python 依赖
      - name: Install dependencies
        run: |
          # 直接安装所需包（setup-python 已确保 pip 可用）
          pip install lxml
          
          # 列出已安装包（用于调试）
          pip list

      # 第六步：生成 EPG 文件
      - name: Generate EPG with Python
        run: |
          # 复制脚本和输入文件到临时工作目录
          cp temp_workspace/scripts/epgnew4gtv2_cst.py temp_workspace/
          cp temp_workspace/main_repo/epg4gtv2_cst.xml temp_workspace/
          
          # 切换到临时工作目录运行脚本
          cd temp_workspace
          python epgnew4gtv2_cst.py
          
          # 检查文件是否生成
          if [ ! -f epgnew4gtv2_cst.xml ]; then
            echo "错误: epgnew4gtv2_cst.xml 文件未生成"
            exit 1
          fi
          
          echo "生成文件大小: $(du -h epgnew4gtv2_cst.xml | cut -f1)"

      # 第七步：检出目标仓库
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: yufeilai666/tvepg
          token: ${{ secrets.GITHUB_TOKEN }}
          path: tvepg
          ref: main

      # 第八步：更新目标文件
      - name: Update target file
        run: |
          cp -f temp_workspace/epgnew4gtv2_cst.xml tvepg/epgnew4gtv2_cst.xml
          
          if diff temp_workspace/epgnew4gtv2_cst.xml tvepg/epgnew4gtv2_cst.xml >/dev/null; then
            echo "epgnew4gtv2_cst.xml 文件成功更新"
          else
            echo "错误: epgnew4gtv2_cst.xml 文件复制失败"
            exit 1
          fi

      # 第九步：提交变更
      - name: Commit and push
        working-directory: tvepg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add epgnew4gtv2_cst.xml
          
          if git diff-index --quiet HEAD -- epgnew4gtv2_cst.xml; then
            echo "epgnew4gtv2_cst.xml 文件内容未变化，跳过提交"
          else
            changes=$(git diff --shortstat HEAD -- epgnew4gtv2_cst.xml)
            now_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
            commit_msg="epgnew4gtv2_cst.xml 自动更新: $now_time"
            
            [ -n "$changes" ] && commit_msg="$commit_msg ($changes)"
            
            git commit -m "$commit_msg"
            git push origin main
            echo "变更已提交: $commit_msg"
          fi
