# 暂时弃用
name: 6(弃用) output epgziyong_cst.xml

on:
  #schedule:
    #- cron: '27 */4 * * *'  # 每4小时第27分钟执行
  workflow_dispatch:

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 第一步：检出当前仓库（主分支，获取输入文件）
      - name: Checkout main branch for input file
        uses: actions/checkout@v4
        with:
          ref: main  # 明确指定主分支

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 第三步：安装 Python 依赖
      - name: Install dependencies
        run: |
          pip install lxml
          pip list

      # 第四步：创建临时工作目录并复制文件
      - name: Create temporary workspace and copy files
        run: |
          # 创建临时工作目录
          mkdir -p /tmp/epg_processing
          
          # 复制输入文件到临时目录
          cp epgziyong.xml /tmp/epg_processing/
          
          # 获取脚本分支的脚本文件
          git fetch origin epg_scripts
          git show origin/epg_scripts:convert_utc2cst.py > /tmp/epg_processing/convert_utc2cst.py

      # 第五步：在临时工作目录中运行 Python 脚本
      - name: convert UTC to CST and output XML with Python
        run: |
          cd /tmp/epg_processing
          
          # 运行 Python 脚本
          python convert_utc2cst.py
          
          # 检查文件是否生成
          if [ ! -f epgziyong_cst.xml ]; then
            echo "错误: epgziyong_cst.xml 文件未生成"
            exit 1
          fi
          
          echo "生成文件大小: $(du -h epgziyong_cst.xml | cut -f1)"
          
          # 将生成的文件复制回工作目录
          cp epgziyong_cst.xml $GITHUB_WORKSPACE/

      # 第六步：检出目标仓库
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: yufeilai666/tvepg
          token: ${{ secrets.GITHUB_TOKEN }}
          path: tvepg
          ref: main

      # 第七步：更新目标文件
      - name: Update target file
        run: |
          cp -f epgziyong_cst.xml tvepg/epgziyong_cst.xml
          
          if diff epgziyong_cst.xml tvepg/epgziyong_cst.xml >/dev/null; then
            echo "文件成功更新"
          else
            echo "错误: 文件复制失败"
            exit 1
          fi

      # 第八步：提交变更
      - name: Commit and push
        working-directory: tvepg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add epgziyong_cst.xml
          
          if git diff-index --quiet HEAD -- epgziyong_cst.xml; then
            echo "文件内容未变化，跳过提交"
          else
            changes=$(git diff --shortstat HEAD -- epgziyong_cst.xml)
            now_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
            commit_msg="epgziyong_cst.xml 自动更新: $now_time"
            
            [ -n "$changes" ] && commit_msg="$commit_msg ($changes)"
            
            git commit -m "$commit_msg"
            git push origin main
            echo "变更已提交: $commit_msg"
          fi

      # 第九步：清理临时目录
      - name: Cleanup
        run: rm -rf /tmp/epg_processing